title: 즐길 줄 아는 개발자가 되자
# description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://chonamdoo.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

# navigation:
#  - title: Home
#    url: /index.html
#  - title: About
#    url: /about
#  - title: Contact
#    url: /contact

social:
   github: chonamdoo
  #  twitter: brianmaierjr
   facebook: namduj
   email: psymarine@gmail.com

google_analytics: "UA-58263416-1"
